<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework Condition="'$(Configuration)' == 'Debug2025' Or '$(Configuration)' == 'Release2025'">net8.0-windows</TargetFramework>
	  <TargetFramework Condition="'$(Configuration)' == 'Debug2026' Or '$(Configuration)' == 'Release2026'">net8.0-windows</TargetFramework>
	  <TargetFramework Condition="'$(Configuration)' == 'Debug2027' Or '$(Configuration)' == 'Release2027'">net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DebugSymbols>true</DebugSymbols>
    <AssemblyTitle>SAM.Core.Pdf.Revit</AssemblyTitle>
    <Product>SAM.Core.Pdf.Revit</Product>
    <Copyright>Copyright ©  2021</Copyright>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <Configurations>Debug;Release;Debug2025;Release2025;Debug2026;Release2026;Debug2027;Release2027</Configurations>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <Platforms>x64;AnyCPU</Platforms>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2025|AnyCPU'">
	  <OutputPath>..\..\build\</OutputPath>
	  <DefineConstants>TRACE;Revit2025</DefineConstants>
	  <Optimize>true</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2026|AnyCPU'">
	  <OutputPath>..\..\build\</OutputPath>
	  <DefineConstants>TRACE;Revit2026</DefineConstants>
	  <Optimize>true</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2027|AnyCPU'">
	  <OutputPath>..\..\build\</OutputPath>
	  <DefineConstants>TRACE;Revit2027</DefineConstants>
	  <Optimize>true</Optimize>
	</PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2025|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>DEBUG;TRACE;Revit2025</DefineConstants>
    <DocumentationFile>..\..\build\SAM.Core.Pdf.Revit.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2026|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>DEBUG;TRACE;Revit2026</DefineConstants>
    <DocumentationFile>..\..\build\SAM.Core.Pdf.Revit.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2027|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>DEBUG;TRACE;Revit2027</DefineConstants>
    <DocumentationFile>..\..\build\SAM.Core.Pdf.Revit.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2025|x64'">
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>TRACE;Revit2025</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2026|x64'">
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>TRACE;Revit2026</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2027|x64'">
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>TRACE;Revit2027</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2025|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>DEBUG;TRACE;Revit2025</DefineConstants>
    <DocumentationFile>..\..\build\SAM.Core.Pdf.Revit.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2026|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>DEBUG;TRACE;Revit2026</DefineConstants>
    <DocumentationFile>..\..\build\SAM.Core.Pdf.Revit.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2027|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>DEBUG;TRACE;Revit2027</DefineConstants>
    <DocumentationFile>..\..\build\SAM.Core.Pdf.Revit.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="PdfSharp">
      <Version>6.2.0</Version>
    </PackageReference>
  </ItemGroup>
	<ItemGroup>
		<Reference Include="RevitAPI" Condition="'$(Configuration)' == 'Debug2026' Or '$(Configuration)' == 'Release2026'">
			<HintPath>$(SolutionDir)\references\Revit 2026\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPI" Condition="'$(Configuration)' == 'Debug2027' Or '$(Configuration)' == 'Release2027'">
			<HintPath>$(SolutionDir)\references\Revit 2027\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIIFC" Condition="'$(Configuration)' == 'Debug2026' Or '$(Configuration)' == 'Release2026'">
			<HintPath>$(SolutionDir)\references\Revit 2026\RevitAPIIFC.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIIFC" Condition="'$(Configuration)' == 'Debug2027' Or '$(Configuration)' == 'Release2027'">
			<HintPath>$(SolutionDir)\references\Revit 2027\RevitAPIIFC.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIUI" Condition="'$(Configuration)' == 'Debug2026' Or '$(Configuration)' == 'Release2026'">
			<HintPath>$(SolutionDir)\references\Revit 2026\RevitAPIUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIUI" Condition="'$(Configuration)' == 'Debug2027' Or '$(Configuration)' == 'Release2027'">
			<HintPath>$(SolutionDir)\references\Revit 2027\RevitAPIUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPI" Condition="'$(Configuration)' == 'Debug2025' Or '$(Configuration)' == 'Release2025'">
			<HintPath>$(SolutionDir)\references\Revit 2025\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIIFC" Condition="'$(Configuration)' == 'Debug2025' Or '$(Configuration)' == 'Release2025'">
			<HintPath>$(SolutionDir)\references\Revit 2025\RevitAPIIFC.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIUI" Condition="'$(Configuration)' == 'Debug2025' Or '$(Configuration)' == 'Release2025'">
			<HintPath>$(SolutionDir)\references\Revit 2025\RevitAPIUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
</Project>