<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework Condition="'$(Configuration)' == 'Debug2025' Or '$(Configuration)' == 'Release2025'">net8.0-windows</TargetFramework>
	  <TargetFramework Condition="'$(Configuration)' == 'Debug2026' Or '$(Configuration)' == 'Release2026'">net8.0-windows</TargetFramework>
	  <TargetFramework Condition="'$(Configuration)' == 'Debug2027' Or '$(Configuration)' == 'Release2027'">net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>SAM_Revit</AssemblyTitle>
    <Product>SAM_Revit</Product>
    <Copyright>Copyright (c) 2020-2026 Michal Dengusiak &amp; Jakub Ziolkowski and contributors</Copyright>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <Configurations>Debug;Release;Debug2025;Release2025;Debug2026;Release2026;Debug2027;Release2027</Configurations>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\build\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2025|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>DEBUG;TRACE;Revit2025</DefineConstants>
    <DocumentationFile>..\..\build\SAM.Architectural.Revit.xml</DocumentationFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2026|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>DEBUG;TRACE;Revit2026</DefineConstants>
    <DocumentationFile>..\..\build\SAM.Architectural.Revit.xml</DocumentationFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2027|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>DEBUG;TRACE;Revit2027</DefineConstants>
    <DocumentationFile>..\..\build\SAM.Architectural.Revit.xml</DocumentationFile>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2025|AnyCPU'">
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>TRACE;Revit2025</DefineConstants>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2026|AnyCPU'">
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>TRACE;Revit2026</DefineConstants>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release2027|AnyCPU'">
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>TRACE;Revit2027</DefineConstants>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Classes\**" />
    <EmbeddedResource Remove="Classes\**" />
    <None Remove="Classes\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAM.Core.Revit\SAM.Core.Revit.csproj" />
    <ProjectReference Include="..\SAM.Geometry.Revit\SAM.Geometry.Revit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
	<ItemGroup>
		<Reference Include="RevitAPI" Condition="'$(Configuration)' == 'Debug2026' Or '$(Configuration)' == 'Release2026'">
			<HintPath>$(SolutionDir)\references\Revit 2026\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPI" Condition="'$(Configuration)' == 'Debug2027' Or '$(Configuration)' == 'Release2027'">
			<HintPath>$(SolutionDir)\references\Revit 2027\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIIFC" Condition="'$(Configuration)' == 'Debug2026' Or '$(Configuration)' == 'Release2026'">
			<HintPath>$(SolutionDir)\references\Revit 2026\RevitAPIIFC.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIIFC" Condition="'$(Configuration)' == 'Debug2027' Or '$(Configuration)' == 'Release2027'">
			<HintPath>$(SolutionDir)\references\Revit 2027\RevitAPIIFC.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIUI" Condition="'$(Configuration)' == 'Debug2026' Or '$(Configuration)' == 'Release2026'">
			<HintPath>$(SolutionDir)\references\Revit 2026\RevitAPIUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIUI" Condition="'$(Configuration)' == 'Debug2027' Or '$(Configuration)' == 'Release2027'">
			<HintPath>$(SolutionDir)\references\Revit 2027\RevitAPIUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPI" Condition="'$(Configuration)' == 'Debug2025' Or '$(Configuration)' == 'Release2025'">
			<HintPath>$(SolutionDir)\references\Revit 2025\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIIFC" Condition="'$(Configuration)' == 'Debug2025' Or '$(Configuration)' == 'Release2025'">
			<HintPath>$(SolutionDir)\references\Revit 2025\RevitAPIIFC.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIUI" Condition="'$(Configuration)' == 'Debug2025' Or '$(Configuration)' == 'Release2025'">
			<HintPath>$(SolutionDir)\references\Revit 2025\RevitAPIUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="SAM.Architectural">
		  <HintPath>..\..\..\SAM\build\SAM.Architectural.dll</HintPath>
		</Reference>
		<Reference Include="SAM.Core">
		  <HintPath>..\..\..\SAM\build\SAM.Core.dll</HintPath>
		</Reference>
		<Reference Include="SAM.Geometry">
		  <HintPath>..\..\..\SAM\build\SAM.Geometry.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
